### ISSUE TITLE
I wrote this request to nostar for dudestar but continue to delete my report

### ISSUE THREAD

**Issue by IW8ELN** [Teeed/WHOis-HS#5]
Deactivate the connection to our DStar systems

The system in DStar creates countless functional problems for our network.
Then turn off the selection on the following ports and reflectors.

REF080 A (Standard ICOM Reflector)
XRF113 A (Standard XRF)
XRF001 A (XLX001 A)
XRF024 A (XLX024 A)
XRF093 A (XLX093 A)
XRF486 A (XLX486 A)

**Comment by Teeed** [comment]
Can you describe what problems do you have in mind?

**Comment by IW8ELN** [comment]
The connection in DStar drops the connections of other systems, brings with it the names of other users and creates loops.
Yesterday I found 27 systems disconnected following the connection of a user who was using dudestar in DStar mode.

**Comment by Teeed** [comment]
Then please fix DStar server software. 

Also, posting this in here (in my another project that has nothing to do with nostar) was quite disrespectful. Closing this one, since this issue do not bother WHOis-HS. There are more appropriate ways to talk about nostar.
